### ISSUE TITLE
Populate Username and ID for Posts in Threads and for single Posts

### ISSUE THREAD

**Issue by alsami** [NubCoda/MEAN-Board#10]
We need to populate more user-info for posts in thread.
When selecting a thread, posts are populated but the field "updatedBy" only delivers the users id.
I need to display the name of the user who has updated the post because we will link to his profile. So I need his Id and his name please.

I.E. : Last updated by "sami" @day n' time XYZ

This will also be needed for a single post-view. Thanks in advance alex :)!

**Comment by lxkrmr** [comment]
1) when selecting a thread / get thread by id
- thread atrribute createdBy is populated
- thread atrribute posts is populated with every attribute except parent

**Comment by lxkrmr** [comment]
2) when selecting a post / get post by id
- post attribute createdBy is populated
- post attribute updatedBy is populated

3) add this deepPopulate statements also to the debug routes / get all Posts or Threads

Pls reopen if you need something else

**Comment by lxkrmr** [comment]
fyi i merge your branch into mine and resolved some minor conflicts.
i also merged this state into the master

so you can also merge the master or my branch into yours, no cherry pick needed ;)
https://github.com/NubCoda/MEAN-Board/commit/b01d03eb2c886fe33fda7c6446bfc822c5d2cfc0

**Comment by lxkrmr** [comment]
reopen because of deepPopulateConfig see #11

**Comment by lxkrmr** [comment]
i adapted it see #11

**Comment by alsami** [comment]
When selecting a single post:
- we also need the information "deletedAt" if the item was deleted previously
- we need to populate the parent thread and the thread parents. Id & title should be enough for now

**Comment by lxkrmr** [comment]
As requested I
- added deletedAt to select
- and extended the population of parents, so you will get the _id, title and parent for
  parent === thread
  parent.parent === e.g. sub sub category
  parent.parnet.parent === e.g. sub category
  parent.parent.parent.parent === e.g. main category

Sadly there is no generic way, so we have to reopen this bug, if we want to dig deeper, but I think for now we are fine.

I merge the changes to the master branch
https://github.com/NubCoda/MEAN-Board/commit/2e228b8cd24dbbd60e873aa5bf31409102518711
