### ISSUE TITLE
Populating more data for post-actions

### ISSUE THREAD

**Issue by alsami** [NubCoda/MEAN-Board#13]
When creating, updating or deleting posts, we need to populate more information about the post to display the new post-data properly in the users view.

When creating a post:
- createdBy needs to return the users name and the users id

When updating a post:
- updatedBy needs to return the users name and the users id
- updatedAt needs to be delivered too

When deleting a post:
- updatedBy needs to return the users name and the users id
- deletedAt needs to be delivered too

**Comment by lxkrmr** [comment]
https://github.com/NubCoda/MEAN-Board/commit/00178ae1a6cedcf92abba4d5f11687a64252045b

a) you will get createdAt, updatedAt, deletedAt for every route now

b) creating a post
still have to fix an acl problem but now you will get a populated post obj with the requested info:
createdBy / userName / _id

c) updating a user
- userName + _id
- updatedAt

d) deleting:
sure? I added some functionality that you won't get the post if it is soft-deleted.
As bob marley said: no post no cry

**Comment by lxkrmr** [comment]
As discussed closed for the moment
