### ISSUE TITLE
No permissions to access inbox routes

### ISSUE THREAD

**Issue by TimS95** [NubCoda/MEAN-Board#17]
Can't acces the inbox route, because i dont have the permissions. Think it is a problem with the acl.

**Comment by lxkrmr** [comment]
Please provide more informations!!!! Error message your behavior. How do you call the route! Which is your user role? Does postman work? It is not a ISSUE to write don't work without checking your infos

**Comment by lxkrmr** [comment]
you are using the wrong route:
./javascripts/user.js:          return $http.get('/api/inbox').success(function(data) {

it have to be:
localhost:3000/api/message/inbox

Otherwise you get an ValueError for the ACL that is trying to read some information for inbox instead of message
