### ISSUE TITLE
populating deeper than deep?

### ISSUE THREAD

**Issue by alsami** [NubCoda/MEAN-Board#2]
We need to populate the childs parent 2 levels deeper than now. (or up) :smiley: 

![fehler1](https://cloud.githubusercontent.com/assets/2729205/7349938/dabed14c-ecfc-11e4-8ea9-502c25c641bc.PNG)

**Comment by lxkrmr** [comment]
now we are going deeper and upper at the same time:
categories.categories.categories.parent

yes we now that is the same as categories.categories but categories.categories.categories needs to know his parent ;)

pls reopen if it still does not work
