### ISSUE TITLE
make email and password private

### ISSUE THREAD

**Issue by TimS95** [NubCoda/MEAN-Board#3]
Never deliver the password of a user to the frontend.

If it is not the current user, do not deliver the email of the user.

**Comment by lxkrmr** [comment]
I added a 'select' to the routes:
- get alle user and
- get a specific user by id

now you will only get the following informations (of course only if there is a value):
- firstName
- lastName
- birthday
- gender
- userName
- country

If you need more pls reopen this issue.

**Comment by lxkrmr** [comment]
btw: use
git merge alex

to merge this changes to your branch. But be carfeful there are some conflicts between the branches atm.

Otherwise you can cherry pick the changes:
https://github.com/NubCoda/MEAN-Board/commit/983acb1365e7ca453ac55b96166e6f2fbdc2d30a
