### ISSUE TITLE
User permissions: diggin deeper

### ISSUE THREAD

**Issue by alsami** [NubCoda/MEAN-Board#4]
We also need some kind of flag to check whether the user is an admin/ moderator or not. We might need more permissions later but that should be fine for now.

**Comment by alsami** [comment]
Our board should have 4 permission groups:
- Admin
- Moderator
- User
- Visitor

Admin:
Create, update, delete or punish Users
Create, update or delete categories
Create, update or delete threads
Create, update or delete posts

Moderator:
Punish Users (excluding permant bann, we will discuss this later)
Create, update or delete threads
Create, update or delete posts

User:
Create, update his own threads
Create, update his own posts

Visitor:
View everything, that is not restricted not anything.
Despite that he does nothing.

**Comment by lxkrmr** [comment]
I have already added the function: requireLogin to avoid that someone can create posts, threads or categories without beeing registered.

I also started with the user permission, but still have some troubles. See:
https://github.com/NubCoda/MEAN-Board/commit/e38bf30618091c98064ceab097ff4ed41cecc9d3

Afap I'll implement permissions groups for the mod and admin permission system

**Comment by lxkrmr** [comment]
It getting complex. Looks like we need some ACLs, e.g.

acl = {
  guest: {
    user: {
      get: true,
      post: true,
      update: false,
      delete: false
    }
  ...
  }
  ...
}

**Comment by lxkrmr** [comment]
I implemented the permission system like this:

(1) secure API
the server checks what user role tries call which http method on which uri.
for this i implemented a object structur as an access control list (acl)

(2) check detailed permission
if you have the permission to call the uri with the choosen method, the server checks if you are a admin, or moderator or a user that creates the requested object. if so the transaction is permitted otherwise you will get a 403.

future tm:
- i think we have to add more details to this system
- and we have to think about punishing users 

known issues:
updating a user as an admin will cause switching to this user ;)
e.g. foobar as an admin updates the user spam to promote him/her role to a moderator. after updating fobbar is logged in as spam ^^

**Comment by lxkrmr** [comment]
FIXED: switching user during update

BUT:
int the future TM, i have to implemeted a weight to the roles, because e.g.:

currently a moderator is able to update and delete an admin ;)

**Comment by lxkrmr** [comment]
extend ACL

1) add weight or prio 
e.g. to avoid that moderator can update or delete an admin or moderator

2) make custom roles possible
e.g. to add more roles like diffrent moderators

3) add acls for object attributes / properties
e.g. to avoid that a user can undo deletedAt, change his / her role ...

**Comment by lxkrmr** [comment]
I had some ideas:

to 1) add weight or prio
I thought a lot about numbers, for example if it possible to use a number like 666 to rule over everything else less than this. Not bad, but this could be complicated, e.g.:

I have the role user with a number of 0.815 and the role moderator with the number 666. Now i could use 0.815 < 666 to say that the moderator is able to update the user but not the other way around.

But what will happen if we will extend the roles?
- mod2.0
-  user2.0

Task: Old moderators shouldn't have permission to update mod2.0 and user2.0 but mod2.0 should be able to do it. PROBLEM: just a simple number will not do the trick ;)

BUT a prime can! a prime numbers has no positive divisors other than 1 and itself. And every ('small') number that is not a prime can be build (in just one way) out of prime numbers.

Confused? Good! ;):

Each role will get an unique prime number called access_key and an attribute called editable_by
- admin.access_key = 3, admin.editable_by = 3
- moderator.access_key = 5, moderator.editable_by = 15 (3*5)
- user.access_key = 7, user.editable_by = 105 (3_5_7)

If you now want to know if an role can edit another you can do this:
role01.editable_by % role02.access_key === 0

This statement is only true if the editable_by value is a product of the roles that should have access.

We add to more roles:
- admin.access_key = 3, admin.editable_by = 3
- moderator.access_key = 5, moderator.editable_by = 15 (3*5)
- user.access_key = 7, user.editable_by = 105 (3_5_7)
- mod2.0.access_key = 11, mod2.0.editable_by = 33 (3*11)
- user2.0.access_key = 13, user2.0.editable_by = 429 (3_11_13)
- user3.0.access_key = 17, user3.0.editable_by = 2805 (3_5_11*17)

This means:
mod2.0 is editable by admin and itself
user2.0 is editable by admin, mod2.0 and itself
user3.0 is editable by admin, moderator, mod2.0 and itself

**Comment by lxkrmr** [comment]
to 3) add acls for object attributes / properties

I think it could be possible to extend the acls like this:
- old: acl[role][model][method] = true
- old e.g.: acl[moderator][user][put] = true
- new: acl[role][model][method] = ['attrib01', 'attrib02', 'attrib03', ...]
- new e.g.: acl[moderator][user][put] = ['firstName', 'lastName', ...]

This list of attributes can be used to pick only the allowed data out of the req.body

allowed_attributes = acl[moderator][user][put] // firstName, ...
req.body; // {firstName: 'foo', password: 'youAreHacked'}

allowed_attributes.forEach(function(attrib, key)){
    // check if there is a value and add it to the update_objs, only this will be used for updates
});

**Comment by lxkrmr** [comment]
we are now able to specify allowed attributes for models by role ;) for example: right now only a admin
is able to update the role attribute on a User-Model, so if you don't have an admin user, go an update one before pulling this changes ^^

fyi: we can add this behaviour to every update and post route and of course to every get and delete route but i don't think we will need this.

atm: i leave it like it is - meaning: i adapted the users route
https://github.com/NubCoda/MEAN-Board/commit/8e895ab2d2a7397a7890b2853be4d4023ec19c25

**Comment by lxkrmr** [comment]
idea: 2 steps

first step) use prime numbers to check if the user is allowd to access the route
second step) if the user is allowed to access get a list of permitted attributes to generate a permitted object

**Comment by lxkrmr** [comment]
now it is no longer possible for a moderator to update another moderator or admin except her- / himself
https://github.com/NubCoda/MEAN-Board/commit/5a335d9e116ff7c0477308380f4b404a9f4dfe25

BUT I have a strange feeling that this is not the best way of doing things. There must e a generic way to work with prime numbers, but for not I would suggest to stop here and leave it to my future me to handle it, if we will be at the point to need this ^^ So closed...
